/* berries-config.js */
(function (global) {
  const inventoryItems = [
    {
      id: 'pine-cone',
      titleRu: 'Шишка',
      assetUrl: './img/rare/pine-cone.png',
      widthPx: 34,
      heightPx: 34,
      inventoryItem: true,
    },
    {
      id: 'colorado-beetle',
      titleRu: 'Колорадский жук',
      assetUrl: './img/rare/colorado-beetle.png',
      widthPx: 36,
      heightPx: 30,
      inventoryItem: true,
    },
    {
      id: 'nail-puller',
      titleRu: 'Гвоздодёр',
      assetUrl: './img/scenario-drop/nail-puller.png',
      widthPx: 50,
      heightPx: 38,
      inventoryItem: true,
    },
    {
      id: 'kettle',
      titleRu: 'Котелок',
      assetUrl: './img/scenario-drop/kettle.png',
      widthPx: 46,
      heightPx: 46,
      inventoryItem: true,
    },
    {
      id: 'axe',
      titleRu: 'Топор',
      assetUrl: './img/scenario-drop/axe.png',
      widthPx: 48,
      heightPx: 48,
      inventoryItem: true,
    },
  ];

  /** @type {{id:string,titleRu:string,assetUrl:string,widthPx:number,heightPx:number,primitive:{base?:string,highlight?:string,kind?:string,cap?:string,stem?:string,spots?:string,root?:string,leaf?:string},bushType?:string,bushScale?:number,bushAssetUrl?:string,bushPrimitive?:{kind?:string,cap?:string,capShade?:string,stem?:string,grass?:string,spots?:string,root?:string,leaf?:string,shadow?:string}}[]} */
  const berries = [
    {
      id: 'strawberry',
      titleRu: 'Клубника',
      assetUrl: './img/berry/strawberry.png',
      profit: 1,
      unlockCost: 0,
      maxSpawnRadius: 10,
      widthPx: 28,
      heightPx: 28,
      bushAssetUrl: './img/berry/strawberry-bush.png',
      bushWidthPx: 84,
      bushHeightPx: 70,
      bushAnchorY: 0.72,
      primitive: { base: '#e11', highlight: 'rgba(255,255,255,0.65)' },
    },
    {
      id: 'blueberry',
      assetUrl: './img/berry/blueberry.png',
      titleRu: 'Черника',
      profit: 2,
      unlockCost: 10,
      maxSpawnRadius: 10,
      widthPx: 24,
      heightPx: 24,
      bushAssetUrl: './img/berry/blueberry-bush.png',
      bushWidthPx: 84,
      bushHeightPx: 70,
      bushAnchorY: 0.72,
      primitive: { base: '#7a3cff', highlight: 'rgba(255,255,255,0.55)' },
    },
    {
      id: 'raspberry',
      assetUrl: './img/berry/raspberry.png',
      titleRu: 'Ежевика',
      profit: 3,
      unlockCost: 50,
      maxSpawnRadius: 10,
      widthPx: 26,
      heightPx: 26,
      bushAssetUrl: './img/berry/raspberry-bush.png',
      bushWidthPx: 84,
      bushHeightPx: 70,
      bushAnchorY: 0.72,
      primitive: { base: '#241338', highlight: 'rgba(255,255,255,0.5)' },
    },
    {
      id: 'champignon',
      titleRu: 'Шампиньон',
      profit: 4,
      unlockCost: 250,
      minSpawnRadius: 7,
      assetUrl: './img/berry/champignon.png',
      widthPx: 44,
      heightPx: 44,
      bushWidthPx: 87,
      bushHeightPx: 87,
      bushScale: 0.79,
      primitive: {
        kind: 'mushroom',
        cap: '#f4eee6',
        stem: '#e1d2bf',
        spots: 'rgba(255,255,255,0.85)',
      },
      bushType: 'centered',
      bushAssetUrl: './img/berry/champignon-bush.png',
      bushPrimitive: {
        kind: 'mushroom',
        cap: '#f2e9dd',
        capShade: '#d6c7b4',
        stem: '#e6d7c3',
        grass: '#1f8b45',
        spots: '#ffffff',
        shadow: 'rgba(0,0,0,0.2)',
      },
    },
    {
      id: 'beet',
      titleRu: 'Свёкла',
      profit: 5,
      unlockCost: 1250,
      minSpawnRadius: 7,
      assetUrl: './img/berry/beet.png',
      widthPx: 36,
      heightPx: 44,
      bushWidthPx: 92,
      bushHeightPx: 98,
      bushScale: 0.9,
      primitive: {
        kind: 'beet',
        root: '#9b1b30',
        leaf: '#2f9b52',
        highlight: 'rgba(255,255,255,0.45)',
      },
      bushType: 'centered',
      bushAssetUrl: './img/berry/beet-bush.png',
      bushPrimitive: {
        kind: 'beet',
        root: '#8a1227',
        leaf: '#2f9b52',
        grass: '#1b7d3e',
        shadow: 'rgba(0,0,0,0.2)',
      },
    },
    {
      id: 'radish',
      titleRu: 'Редиска',
      profit: 6,
      unlockCost: 2250,
      minSpawnRadius: 7,
      assetUrl: './img/berry/radish.png',
      widthPx: 46,
      heightPx: 53,
      bushAssetUrl: './img/berry/radish-bush.png',
      bushWidthPx: 110,
      bushHeightPx: 118,
      bushScale: 1.08,
      primitive: {
        kind: 'beet',
        root: '#e03939',
        leaf: '#39b36b',
        highlight: 'rgba(255,255,255,0.45)',
      },
      bushType: 'centered',
      bushPrimitive: {
        kind: 'beet',
        root: '#d73232',
        leaf: '#39b36b',
        grass: '#1b7d3e',
        shadow: 'rgba(0,0,0,0.2)',
      },
    },
    {
      id: 'pine',
      assetUrl: './img/mineable/pine1.png',
      titleRu: 'Сосна',
      profit: 6,
      unlockCost: 2000,
      minSpawnRadius: 8,
      widthPx: 110,
      heightPx: 174,
      bushType: 'centered',
      bushScale: 1,
      bushAssetUrl: './img/mineable/pine1.png',
      bushAssetUrls: [
        './img/mineable/pine1.png',
        './img/mineable/pine2.png',
        './img/mineable/pine3.png',
        './img/mineable/pine4.png',
      ],
      assetAnchorY: 0.86,
      resourceType: 'extractable',
      collider: true,
      colliderRadius: 2,
      colliderBoxStages: [
        { x: 1, y: 1 },
        { x: 1, y: 1 },
        { x: 0, y: 1 },
        { x: 0, y: 0 },
      ],
      extractStages: [1, 0.82, 0.66, 0.5],
      extractHarvestMs: 700,
      extractParticleAssetUrl: './img/mineable/log-pine.png',
      extractParticleWidthPx: 50,
      extractParticleHeightPx: 38,
      rareDrops: [
        { id: 'pine-cone', chance: 0.01, on: 'final' },
      ],
      primitive: {
        kind: 'tree',
        trunk: '#6d4a2f',
        foliage: '#1f6a32',
        accent: '#2d8845',
        form: 'pine',
      },
      bushPrimitive: {
        kind: 'tree',
        trunk: '#6d4a2f',
        foliage: '#1f6a32',
        accent: '#2d8845',
        form: 'pine',
      },
    },
    {
      id: 'birch',
      assetUrl: './img/mineable/tree1.png',
      titleRu: 'Берёза',
      profit: 7,
      unlockCost: 3000,
      minSpawnRadius: 9,
      widthPx: 118,
      heightPx: 160,
      bushType: 'centered',
      bushScale: 1,
      bushAssetUrl: './img/mineable/tree1.png',
      bushAssetUrls: [
        './img/mineable/tree1.png',
        './img/mineable/tree2_.png',
        './img/mineable/tree3.png',
        './img/mineable/tree4.png',
      ],
      assetAnchorY: 0.86,
      resourceType: 'extractable',
      collider: true,
      colliderRadius: 2,
      colliderBoxStages: [
        { x: 1, y: 1 },
        { x: 1, y: 1 },
        { x: 0, y: 1 },
        { x: 0, y: 0 },
      ],
      extractStages: [1, 0.84, 0.68, 0.52],
      extractHarvestMs: 700,
      extractParticleAssetUrl: './img/mineable/log-birch.png',
      extractParticleWidthPx: 50,
      extractParticleHeightPx: 38,
      primitive: {
        kind: 'tree',
        trunk: '#d6c8b3',
        foliage: '#3c8f4d',
        accent: '#58a95f',
        form: 'round',
      },
      bushPrimitive: {
        kind: 'tree',
        trunk: '#d6c8b3',
        bark: '#a5907a',
        foliage: '#3c8f4d',
        accent: '#58a95f',
        form: 'round',
      },
    },
    {
      id: 'dead-tree',
      titleRu: 'Мертвое дерево',
      assetUrl: './img/mineable/dead_tree1.png',
      profit: 8,
      unlockCost: 5000,
      minSpawnRadius: 9,
      maxSpawnRadius: 18,
      widthPx: 124,
      heightPx: 154,
      bushType: 'centered',
      bushScale: 1,
      bushAssetUrl: './img/mineable/dead_tree1.png',
      bushAssetUrls: [
        './img/mineable/dead_tree1.png',
        './img/mineable/dead_tree2.png',
        './img/mineable/dead_tree3.png',
        './img/mineable/dead_tree4.png',
      ],
      assetAnchorY: 0.86,
      surfaceTypes: ['dead'],
      resourceType: 'extractable',
      collider: true,
      colliderRadius: 2,
      colliderBoxStages: [
        { x: 1, y: 1 },
        { x: 1, y: 1 },
        { x: 0, y: 1 },
        { x: 0, y: 0 },
      ],
      extractStages: [1, 1, 1, 1],
      extractHarvestMs: 700,
      extractParticleAssetUrl: './img/mineable/log-dead.png',
      extractParticleWidthPx: 52,
      extractParticleHeightPx: 36,
      primitive: {
        kind: 'tree',
        trunk: '#3b423a',
        foliage: '#3b423a',
        accent: '#596158',
        form: 'dead',
      },
      bushPrimitive: {
        kind: 'tree',
        trunk: '#3b423a',
        bark: '#596158',
        foliage: '#3b423a',
        accent: '#596158',
        form: 'dead',
      },
    },
    {
      id: 'snow-pine',
      titleRu: 'Снежная ель',
      assetUrl: './img/mineable/snow_pine1.png',
      profit: 9,
      unlockCost: 6500,
      minSpawnRadius: 9,
      maxSpawnRadius: 24,
      widthPx: 112,
      heightPx: 178,
      bushType: 'centered',
      bushScale: 1,
      bushAssetUrl: './img/mineable/snow_pine1.png',
      bushAssetUrls: [
        './img/mineable/snow_pine1.png',
        './img/mineable/snow_pine2.png',
        './img/mineable/snow_pine3.png',
        './img/mineable/snow_pine4.png',
      ],
      assetAnchorY: 0.86,
      surfaceTypes: ['snow'],
      resourceType: 'extractable',
      collider: true,
      colliderRadius: 2,
      colliderBoxStages: [
        { x: 1, y: 1 },
        { x: 1, y: 1 },
        { x: 0, y: 1 },
        { x: 0, y: 0 },
      ],
      extractStages: [1, 1, 1, 1],
      extractHarvestMs: 700,
      extractParticleAssetUrl: './img/mineable/log-snow-pine.png',
      extractParticleWidthPx: 52,
      extractParticleHeightPx: 36,
      rareDrops: [
        { id: 'pine-cone', chance: 0.01, on: 'final' },
      ],
      primitive: {
        kind: 'tree',
        trunk: '#6d4a2f',
        foliage: '#1f6a32',
        accent: '#f2fbff',
        form: 'pine',
      },
      bushPrimitive: {
        kind: 'tree',
        trunk: '#6d4a2f',
        foliage: '#1f6a32',
        accent: '#f2fbff',
        form: 'pine',
      },
    },
    {
      id: 'potato',
      titleRu: 'Куст картофеля',
      profit: 7,
      unlockCost: 3250,
      minSpawnRadius: 7,
      assetUrl: './img/berry/potato.png',
      widthPx: 50,
      heightPx: 43,
      bushAssetUrl: './img/berry/potato-bush.png',
      bushWidthPx: 115,
      bushHeightPx: 110,
      bushScale: 1.08,
      rareDrops: [
        { id: 'colorado-beetle', chance: 0.01, on: 'final' },
      ],
      primitive: {
        kind: 'beet',
        root: '#c6a46c',
        leaf: '#6f9c45',
        highlight: 'rgba(255,255,255,0.4)',
      },
      bushType: 'centered',
      bushPrimitive: {
        kind: 'beet',
        root: '#b89355',
        leaf: '#6f9c45',
        grass: '#1b7d3e',
        shadow: 'rgba(0,0,0,0.2)',
      },
    },
    {
      id: 'tomato',
      assetUrl: './img/berry/tomato.png',
      titleRu: 'Куст помидоров',
      profit: 8,
      unlockCost: 4250,
      minSpawnRadius: 7,
      widthPx: 26,
      heightPx: 26,
      bushAssetUrl: './img/berry/tomato-bush.png',
      bushWidthPx: 84,
      bushHeightPx: 70,
      bushAnchorY: 0.72,
      primitive: { base: '#e63a2f', highlight: 'rgba(255,255,255,0.5)' },
    },
  ];

  /** Веса ресурсов (пока все = 1) */
  function getResourceWeight(index) {
    return 1;
  }

  global.BerriesConfig = {
    berries,
    inventoryItems,
    getResourceWeight,
  };
})(window);
